# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='optionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('isCorrect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='quest_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.categories')),
            ],
        ),
        migrations.CreateModel(
            name='testQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('multichoice', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='quest_cate',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.testQuestion'),
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.testQuestion'),
        ),
    ]
