# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testEng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('meaning', models.CharField(max_length=1000)),
                ('pronunc', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.user')),
            ],
        ),
        migrations.CreateModel(
            name='word_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='word_cate',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.category'),
        ),
        migrations.AddField(
            model_name='word_cate',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.user'),
        ),
        migrations.AddField(
            model_name='topic',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testEng.user'),
        ),
    ]
