# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testEng', '0002_auto_20160512_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id_user',
        ),
    ]
