# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testEng', '0004_word_islearned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='isLearned',
            new_name='tolearn',
        ),
    ]
