# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEng', '0006_auto_20160515_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
