# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testEng', '0008_word_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testEng.user'),
        ),
    ]
