# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testEng', '0010_word_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id_user',
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
